### ISSUE TITLE
New service throwing error when no samples involved

### ISSUE THREAD

**Issue by GuilleGorines** [BU-ISCIII/buisciii-tools#110]
When there are no samples linked to the service in iSKYlims, the "new-service" module will throw a somewhat ugly error.

![Captura de pantalla de 2023-01-11 12-54-54](https://user-images.githubusercontent.com/60110848/211800149-f50455f4-7d01-4561-bd26-a74b8ca100bf.png)

This, obvious as it seems, could perhaps be handled more elegantly by throwing a warning instead of the whole error, or even a prompt to ask whether generate the directory scaffold without linking the samples. This would make the tools a little smoother to work with when the samples are provided externally (and as a consequence, not loaded on iSKYlims).

Delete this issue if not on board with the idea plz!

**Comment by Daniel-VM** [comment]
Working on it 👍🏾
