### ISSUE TITLE
Big junk files that should be deleted in trio services

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/buisciii-tools#198]
There's a file named `dbNSFP_ENSG_plugin_Columns.txt` that is generated during 03-annotation process in both EXOMETRIO and WGSTRIO services.

The size of this file is roughly 24GB, and should be included in each of these templates [lablog](https://github.com/BU-ISCIII/buisciii-tools/blob/main/bu_isciii/templates/wgstrio/ANALYSIS/ANALYSIS01_GENOME/lablog) so its deleted properly.

**Comment by saramonzon** [comment]
Yes, as a big file we should delete it using srun in the lablog, add it in the next PR please!

**Comment by Shettland** [comment]
Fixed: https://github.com/BU-ISCIII/buisciii-tools/pull/260
