### ISSUE TITLE
Files that should be included in clean process for rna-seq template

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/buisciii-tools#199]
`Aligned.out.bam `and `Aligned.toTranscriptome.out.bam` are intermediate files for each sample that are generated during rna-seq's nextflow pipeline but are not used in later processes of the service. The size of these files is ussually enough to be taken into consideration for removal during cleaning of the folders.

I'd recommend adding to "files" in https://github.com/BU-ISCIII/buisciii-tools/blob/main/bu_isciii/templates/services.json:

https://github.com/BU-ISCIII/buisciii-tools/blob/3accca9be01a9c9a5c07ebc7f63e771c91968ccf/bu_isciii/templates/services.json#L139-L150

**Comment by saramonzon** [comment]
@Shettland I agree, add them to the json in the next PR you prepare!
Do you agree @svarona ?

**Comment by saramonzon** [comment]
Mm reading another issue, if they are big big files we should consider a separate sh script in the lablog for deleting them using srun for now? until we revisit the clean module to see if we can include a srun deletion process

**Comment by svarona** [comment]
`Aligned.toTranscriptome.out.bam` might be needed in case of differential expressed transcripts?
Maybe it would be better a custom script from which we could delete `Aligned.toTranscriptome.out.bam` or any other .bam in specific cases so they won't be deleted.

**Comment by jaimeozaez** [comment]
Done. Files set in services.json file and they will be removed from rnaseq services when clean module runs.

**Comment by jaimeozaez** [comment]
Done. Files set in services.json file and they will be removed from rnaseq services when clean module runs.
