### ISSUE TITLE
Create new service: define iskylims queries

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/buisciii-tools#2]

**Comment by svarona** [comment]
PARA NEW_SERVICE:
Nosotros le pasaremos al script el resolution ID (e.g. SRVCNM576.1)
Necesitaremos a partir de ese dato:
- La carpeta que tenemos que crear (eg SRVCNM576_20220301_ASSEMBLY275_rabad_S)
- El service_id (e.g. assembly_annotation)
- El service label (e.g. Microbial: Assembly + automatic annotation)

**Comment by luissian** [comment]
Estos son los datos que se enviaría  
[ResolutionResponse.txt](https://github.com/BU-ISCIII/buisciii-tools/files/8112582/ResolutionResponse.txt)
Os parece bien??
