### ISSUE TITLE
Make a thorough review of files and folders to delete in services.json

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/buisciii-tools#223]
Some templates have been updated (leaving the latter files/folders outdated) while others do not have the proper files/samples to clean correctly assigned from the beggining in [services.json](https://github.com/BU-ISCIII/buisciii-tools/blob/main/bu_isciii/templates/services.json). 
e.g. In assembly template, the name of the folder is now "01-processing" 
[["folders":["01-preprocessing/trimmed_sequences"],](https://github.com/BU-ISCIII/buisciii-tools/blob/d95b73843409fd451296bdff4407b21f9d8b3831/bu_isciii/templates/services.json#L11)](https://github.com/BU-ISCIII/buisciii-tools/blob/d95b73843409fd451296bdff4407b21f9d8b3831/bu_isciii/templates/services.json#L11)

**Comment by jaimeozaez** [comment]
Here there is a problem. When we run the “finish” function of the buisciii-tools, it runs first clean, then scratch_to_service, then rename_no_copy and finally the copy-sftp.

The point is that the clean function (which is executed in scratch) includes the _DEL tag in the folders that have been emptied, but there is still a copy of the same folder in /data/bi, and **this folder remains unrenamed**, which ends up being copied to the sftp.

Maybe it would be a good option to include the renaming (_DEL) of the folders inside the rename_no_copy function.

**Comment by jaimeozaez** [comment]
Done!
