### ISSUE TITLE
Update sarek version for Exome and Trio templates

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/buisciii-tools#226]
The current version for Sarek being implemented in the templates is 3.1.1, which is not compatible with Nextflow v23. Right now the latest release for the software is [v3.4.0](https://github.com/nf-core/sarek/releases/tag/3.4.0), which might be compatible. Therefore, I'd recommend updating the version for this pipeline

**Comment by victor5lm** [comment]
Currently, the latest release of sarek is [v3.4.2](https://github.com/nf-core/sarek/releases/tag/3.4.2), which, based on what it is indicated in the _nextflow.config_ file, is compatible with any Nextflow version that is **not** greater than or equal to 23.04.0 (`nextflowVersion = '!>=23.04.0'`). Therefore, the latest release of sarek is still not compatible with Nextflow v23; we'd have to use an older version (22.10.1, 22.04.0, etc).

**Comment by saramonzon** [comment]
Mm, I'm not sure why the `!` but i think that's the required nextflow version you need to run sarek. Upload the pipeline and try it with the latest version of nextflow, but it should work

**Comment by Shettland** [comment]
I'd say its the opposite. As you can see [here](https://github.com/nf-core/sarek/releases/tag/3.2.1), in release 3.2.1 they bumped a new nextflow version so the minimum required Nextflow version for sarek would be 23.04.0. [exact commit](https://github.com/nf-core/sarek/pull/1082/commits/3bcc1040a1023286e115298313acea20376d31ce)

**Comment by victor5lm** [comment]
True, the v3.4.2 release works with Nextflow v23.10.0. I will update the templates then.
