### ISSUE TITLE
Add permission fixing after each service

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/buisciii-tools#227]
We have some issues with the permissions in the HPC
Folder permissions must be set as: `user bi 775` and files as `user bi 664`, for some reason we don't know, sometimes files and/or folders have wrong credentials (user user, or some combination of wrong permissions)

In order to assure once the service is finished the permissions are kept in its correct form, we can add to the finish and/or clean module that the permissions are set as stated above.

It would also be helpful to add a helper script does fix this to any folder, like references or research so we can easily run it when we create a new folder in the HPC if the permissions are wrongly set. This script must be documented in the Wiki.

**Comment by Shettland** [comment]
Isnt this a dup of https://github.com/BU-ISCIII/buisciii-tools/issues/212 ?

**Comment by saramonzon** [comment]
Yes..I don't remember if i completed my mental tasks or not...closing this
