### ISSUE TITLE
Change scratch-copy default queue from idx

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/buisciii-tools#229]
Right now, the default queue to copy files using scratch is `middle_idx`. It would be quite helpful to change it to middle_obx since its less used and saturated. 

https://github.com/BU-ISCIII/buisciii-tools/blob/d95b73843409fd451296bdff4407b21f9d8b3831/bu_isciii/conf/configuration.json#L55-L58

Either way, an extra optional parameter called "--queue" or "--partition" could be introduced to either use idx or obx in case one of the queues is full.

**Comment by victor5lm** [comment]
According to the srun [documentation](https://slurm.schedmd.com/srun.html), and in relation to the `--partition` option: 

> If the job can use more than one partition, specify their names in a comma separate list and the one offering earliest initiation will be used with no regard given to the partition name ordering.

Therefore, I guess the best option would be the following:

```
scratch_path": "/scratch/bi/", 
 "srun_settings": { 
     "--partition": "middle_idx,middle_obx", 
     "--time": "24:00:00",
```
Please let me know whether you agree with this.

**Comment by Shettland** [comment]
> According to the srun [documentation](https://slurm.schedmd.com/srun.html), and in relation to the `--partition` option:
> 
> > If the job can use more than one partition, specify their names in a comma separate list and the one offering earliest initiation will be used with no regard given to the partition name ordering.
> 
> Therefore, I guess the best option would be the following:
> 
> ```
> scratch_path": "/scratch/bi/", 
>  "srun_settings": { 
>      "--partition": "middle_idx,middle_obx", 
>      "--time": "24:00:00",
> ```
> 
> Please let me know whether you agree with this.

Looks good to me!
