### ISSUE TITLE
All lablogs should include lablog in its name

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/buisciii-tools#236]
Make sure that ALL lablogs, like the ones in RESULTS folder, are named with the string `lablog` so they can be skipped in the SFTP copy:
- lablog_pipeline_results

**Comment by Shettland** [comment]
Maybe the title should be "All lablogs should include the string lablog in its name"? Because it can be named different if it at least includes the substring "`lablog"` in it. Like `lablog_viralrecon`.
