### ISSUE TITLE
Check path where nexflow downloads the needed singularity images

### ISSUE THREAD

**Issue by jaimeozaez** [BU-ISCIII/buisciii-tools#269]
We expect every nf-core pipeline to use the necessary singularity-images from /data/bi/pipelines/singularity-images/, and this is the path where the news singularity-images should be downloaded. We have this path configured (or we will have it un a near future) in our ~/.bashrc file, but this path can be "overwritten" by some nextflow config files.

Example case:
For viralrecon, we have the following lines added at the `/data/bi/pipelines/nf-core-viralrecon-2.6.0/workflow/nextflow.config` file:

```
// Added by `nf-core download` v2.3.dev0 //
singularity.cacheDir = "${projectDir}/../singularity-images/"
///////////////////////////////////////% 
```
This triggers the pipeline to use the images from `/data/bi/pipelines/nf-core-viralrecon-2.6.0/workflow/../singularity-images/` and downloading the missing ones inside this path, instead of doing it in the correct path.

This lines must be removed from all the config files (in all nf-core pipelines).

**Comment by saramonzon** [comment]
changed in `pipelines_new` this should be fixed once pipelines_new becames the new pipelines
