### ISSUE TITLE
New release avaliable of nf-core/bacass - v2.4.0

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/buisciii-tools#367]
New version of nf-core bacass is avalable.  You can find the release details [here](https://github.com/nf-core/bacass/releases/tag/2.4.0). Please consider updating the scripts that use this pipeline in the `TEMPLATES` section.

**Comment by victor5lm** [comment]
The 2.4.0 version is already installed within `/data/bi/pipelines/nf-core-bacass`. Is this new version ready to be included in the corresponding scripts or should I wait till some issues related to this new version are solved? @Daniel-VM
