### ISSUE TITLE
Read length inconsisteng in viralrecon

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/buisciii-tools#368]
In the script that creates mapping_illumina stats, read length is failing to determine read length in some samples. Check and fix the code.

https://github.com/BU-ISCIII/buisciii-tools/blob/86556c4ebf0c4a15e848ebef12a1fc0d44c01308/bu_isciii/templates/viralrecon/ANALYSIS/create_summary_report.sh#L45

**Comment by victor5lm** [comment]
Could you please provide an example of when this line fails?
