### ISSUE TITLE
Deliver automatization

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/buisciii-tools#5]
[ ] Copy in sftp
[ ] Update state in iskylims
[ ] Get information from iskylims, user, samples, dates, etc.
[ ] Generate markdown, html and pdf report

**Comment by ErikaKvalem** [comment]
1. Update state in iskylims --> resolution finished 
2.  Copy in sftp
3. Update state in iskylims --> resolution delivered
4. Get info iskylims for reporting 
5. Generate md, html etc

**Comment by saramonzon** [comment]
#15, #21 , #36 , #57 , #53
