### ISSUE TITLE
Create list service and version tools

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/buisciii-tools#7]

**Comment by Alema91** [comment]
Create a visualization of the buisciii tools.

**Comment by Alema91** [comment]
He eliminado la branch en la que estaba trabajando pensando que eso me iba a solucionar un problema de fetch pero me ha generado mas problemas.

**Comment by saramonzon** [comment]
Closed here: https://github.com/BU-ISCIII/buisciii-tools/pull/48
