### ISSUE TITLE
Update iskylims api upon requirements appear

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/buisciii-tools#8]

**Comment by luissian** [comment]
Request:    'drylab/api/services?state=<servicese_state>'
Request:    'drylab/api/resolution?state=<resolution_state>'
Request:    'drylab/api/serviceFullData?service=<service_nuber>'
Request:    'drylab/api/samplesInService?service=<service_number>'
Request:    'drylab/api/update?resolution=<resolution_state>
Request:    'drylab/api/delivery

**Comment by saramonzon** [comment]
@luissian can you upload this list with all the available api requests? I can pin this issue for reference until the api docs are ready

**Comment by saramonzon** [comment]
@luissian this query could output the resolutionFullNumber? I know it is a resolution info, but it is the same for all resolutions and we need it for the archive module so we don't have to call the api for the full number especifically to the resolution.

**Comment by luissian** [comment]
By calling  **'drylab/api/serviceFullData?service=<service_number>'** it returns 3 main blocks.
- Service info, with this data:
   - "pk",
   -  "serviceRequestNumber",
            "serviceStatus",
            "serviceUserId",
            "serviceCreatedOnDate",
            "serviceSeqCenter",
            "serviceAvailableService",
            "serviceFileExt",
            "serviceNotes"
- Resolutions: a list of all resolutions created for the services
   -  "pk",
            "resolutionNumber",
            "resolutionFullNumber",
            "resolutionServiceID",
            "resolutionDate",
            "resolutionEstimatedDate",
            "resolutionOnQueuedDate",
            "resolutionOnInProgressDate",
            "resolutionDeliveryDate",
            "resolutionNotes",
            "resolutionPipelines",
            "availableServices",
- Samples:

Is this request fits, what you need  your archive module???

**Comment by saramonzon** [comment]
Yes! I think so! I'm trying stuff, we'll see on monday 😸
